CREATE TABLE artNew AS
SELECT ITEM, NAME, ORIGIN_ID, DATING, MEDIA
FROM ART;

CREATE TABLE Artists AS
SELECT ARTIST 
FROM ART
WHERE ART.ARTIST IS NOT NULL;

ALTER TABLE Artists
ADD ARTIST_ID int NOT NULL AUTO_INCREMENT PRIMARY KEY;

CREATE TABLE Creation AS
SELECT ITEM, ARTIST_ID
FROM ART
LEFT JOIN Artists
ON ART.ARTIST = Artists.Artist
WHERE ART.ITEM IS NOT NULL;

ALTER TABLE artNew 
ADD FOREIGN KEY (ORIGIN_ID) REFERENCES ORIGIN(ORIGIN_ID);
ALTER TABLE artNew
ADD FOREIGN KEY (ITEM) REFERENCES Creation(ITEM);
ALTER TABLE Creation
ADD FOREIGN KEY (Artist_ID) REFERENCES Artist(ARTIST_ID)





